matrix:
  CI_SCALA_VERSION:
    - 2.12.6

clone:
  git:
    image: plugins/git
    tags: true
    recursive: true
    depth: 50

pipeline:
  restore_cache:
    image: appleboy/drone-sftp-cache
    when:
      ref: [ refs/heads/1.x, refs/tags/*, refs/pull/*/head ]
    secrets: [ sftp_cache_username, sftp_cache_private_key, sftp_cache_server, sftp_cache_path ]
    restore: true
    mount:
      - /drone/.ivy2/cache
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git

  tests:
    image: scalacenter/scala-docs:1.3
    when:
      ref: [ refs/heads/1.x, refs/tags/*, refs/pull/*/head ]
    commands:
      - export DRONE_DIR="/drone"
      - git fetch --tags && git log | head -n 20
      - ./bin/run-ci.sh

  publish:
    image: scalacenter/scala:1.3
    volumes:
      - /scalacenter:/keys
    when:
      event: [ push, tag, deployment ]
      status: success
    commands:
      # To know what we're releasing
      - git log | head -n 20
      - /usr/local/bin/setup_keys.sh
      - /usr/local/bin/store_credentials.sh
      - sbt releaseEarly

  rebuild_cache:
    image: appleboy/drone-sftp-cache
    when:
      ref: [ refs/heads/1.x, refs/tags/*, refs/pull/*/head ]
    secrets: [ sftp_cache_username, sftp_cache_private_key, sftp_cache_server, sftp_cache_path ]

    rebuild: true
    mount:
      - /drone/.ivy2/cache
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git
